site_name: Vishwanathan
site_url: https://github.com/mvishwa27/MkDocs_Project1/docs/documentation
docs_dir: source
site_dir: docs
site_author: VISHWANATHAN
site_description: Site built using MkDocs




# docs_dir: source/docs/documentation
# site_dir: docs/docs/documentation

nav:
   - Home: docs/documentation/index.md
   - About: docs/documentation/about.md
   - Iris: 
         - docs/documentation/iris1.md
         - docs/documentation/iris2.md
         - docs/documentation/iris3.1.md
         - docs/documentation/iris3.2.md
         - iris4:
                - docs/documentation/iris/iris4/iris4.1.md        
         - iris5:
                # - iris/iris5/iris5.1.md
                - docs/documentation/iris/iris5/iris5.1.md

# Repository
repo_name: https://github.com/mvishwa27
repo_url: https://github.com/mvishwa27/MkDocs_Project1



# Configuration

theme:
   name: material
   logo: docs/assets/images/logo.png

   # features:
      # - navigation.tabs
      # - navigation.sections
      # - toc.integrate
   #    - navigation.top
   language: en
   palette:
      - scheme: default
        toggle: 
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode 
        primary: blue
        accent: purple       
      - scheme: slate
        toggle: 
          icon: material/toggle-switch
          name: Switch to light mode 
        primary: teal
        accent: lime 

extra: 
   homepage: https://github.com/mvishwa27/MkDocs_Project1/docs/documentation
   social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/mvishwa27 
      - icon: fontawesome/brands/github-alt
        link: https://github.com/mvishwa27 

 
# plugins:
#    - search



# Copyright
copyright: Copyright &copy; 2022, V$V Technologies Limited <a href="https://github.com/mvishwa27">(VISHWA)</a>

# theme name: readthedocs



   
